#!/bin/sh 
echo "0123 - ZSP"

. ../tests/common.sh

# generators
for i in 1 2 3; do cp "$MTX_TEST_DATA_DIR/Ru-K378.$i" "gen.$i"; done

# seed vectors
zct -Q 1-3 gen.1 seed

#set -x

# Normal spinup (subspace dim = 40)
zsp -Q -b basis1 -s sub1 -q quot1 -g 3 gen seed
compareBinaryWithReference basis1
for i in 1 2 3; do
   compareBinaryWithReference "sub1.$i"
   compareBinaryWithReference "quot1.$i"
done

# Standard basis (subspace dim = 40)
zsp -Q -b std_basis -t -o std_op -g 3 gen seed
compareBinaryWithReference std_basis
compareBinaryWithReference std_op

# Search cyclic vector (not found)
rm -f cyclic
zsp -Q -e -b cyclic -g 3 gen gen.1
if [ -f cyclic ]; then fail "Subspace was created, should have failed"; fi

# Search cyclic vector (found)
for i in 1 2; do cp "$MTX_TEST_DATA_DIR/m11.$i" "m11.$i"; done
rm -f cyclic
zsp -Q -e -b cyclic -g 2 m11 m11.1
compareBinaryWithReference cyclic

