////////////////////////////////////////////////////////////////////////////////////////////////////
// C MeatAxe - Messages.
////////////////////////////////////////////////////////////////////////////////////////////////////


#include "meataxe.h"
#include <stdarg.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>

/// @addtogroup app
/// @{


/* ------------------------------------------------------------------
   Global data
   ------------------------------------------------------------------ */

/// Message level.
/// This value determines which messages generated by mtxMessage
/// output and which are suppressed.
int MtxMessageLevel = 0;

/// Last error code.
int MtxErrNo = 0;

////////////////////////////////////////////////////////////////////////////////////////////////////

void mtxMessage(int level, const char* msg, ...)
{
   if (level > MtxMessageLevel)
      return;
   va_list args;
   va_start(args,msg);
   StrBuffer* sb = sbAlloc(200);
   sbAppend(sb, pexLogPrefix());
   sbVprintf(sb, msg, args);
   sbAppend(sb, "\n");
   fputs(sbData(sb), stdout);
   sbFree(sb);
   va_end(args);
}

/// @}
// vim:fileencoding=utf8:sw=3:ts=8:et:cin
