////////////////////////////////////////////////////////////////////////////////////////////////////
// C MeatAxe - Messages.
////////////////////////////////////////////////////////////////////////////////////////////////////


#include "meataxe.h"
#include <stdarg.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>

/// @addtogroup app
/// @{


/* ------------------------------------------------------------------
   Global data
   ------------------------------------------------------------------ */

/// Message level.
/// This value determines which messages generated by mtxMessage
/// output and which are suppressed.
int MtxMessageLevel = 0;

/// Last error code.
int MtxErrNo = 0;

////////////////////////////////////////////////////////////////////////////////////////////////////

void mtxMessage(int level, const char* msg, ...)
{
   if (level > MtxMessageLevel)
      return;
   va_list args;
   va_start(args,msg);
   vfprintf(stdout, msg, args);
   fputc('\n', stdout);
   va_end(args);
}

/// @}
// vim:fileencoding=utf8:sw=3:ts=8:et:cin
