name: C/C++ CI

on:
  push:
    branches: [ "master", "pex" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: echo "no configure"
    - name: make
      run: make
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: echo "no configure"
    - name: make
      run: make
